general:
  startup_commands: []
  shutdown_commands: []
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: "window_focus"

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '20px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '20px'
    right: '20px'
    bottom: '20px'
    left: '20px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    border:
      enabled: true
      color: '#BD93F9'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '240' or '95%' for slightly transparent windows
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable)
      opacity: '95%'

  other_windows:
    border:
      enabled: true
      color: '#6272A4'

    hide_title_bar:
      enabled: false

    corner_style:
      enabled: false
      style: 'square'

    transparency:
      enabled: false
      opacity: '0%'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    bind_to_monitor: 1

  - name: '2'
    bind_to_monitor: 1

  - name: '3'
    bind_to_monitor: 1

  - name: '4'
    bind_to_monitor: 1

  - name: '5'
    bind_to_monitor: 1

  - name: '6'
    bind_to_monitor: 1

  - name: '7'
    bind_to_monitor: 1

  - name: '8'
    bind_to_monitor: 0

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:
  # Focus windows
  - commands: ["focus --direction left"]
    bindings: ["lwin+h"]
  - commands: ["focus --direction down"]
    bindings: ["lwin+j"]
  - commands: ["focus --direction up"]
    bindings: ["lwin+k"]
  - commands: ["focus --direction right"]
    bindings: ["lwin+l"]

  # Move windows
  - commands: ["move --direction left"]
    bindings: ["lwin+shift+h"]
  - commands: ["move --direction down"]
    bindings: ["lwin+shift+j"]
  - commands: ["move --direction up"]
    bindings: ["lwin+shift+k"]
  - commands: ["move --direction right"]
    bindings: ["lwin+shift+l"]

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['lwin+space']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['lwin+f']

  # Close focused window.
  - commands: ['close']
    bindings: ['lwin+q']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['lwin+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['lwin+r']

  # Change direction of tilling
  - commands: ['toggle-tiling-direction']
    bindings: ['lwin+v']

  # Exit GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['lwin+rctrl+shift+g']

  # Workspaces
  - commands: ["focus --workspace 1"]
    bindings: ["lwin+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["lwin+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["lwin+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["lwin+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["lwin+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["lwin+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["lwin+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["lwin+8"]

  # Move windows across workspaces
  - commands: ["move --workspace 1"]
    bindings: ["lwin+shift+1"]
  - commands: ["move --workspace 2"]
    bindings: ["lwin+shift+2"]
  - commands: ["move --workspace 3"]
    bindings: ["lwin+shift+3"]
  - commands: ["move --workspace 4"]
    bindings: ["lwin+shift+4"]
  - commands: ["move --workspace 5"]
    bindings: ["lwin+shift+5"]
  - commands: ["move --workspace 6"]
    bindings: ["lwin+shift+6"]
  - commands: ["move --workspace 7"]
    bindings: ["lwin+shift+7"]
  - commands: ["move --workspace 8"]
    bindings: ["lwin+shift+8"]

  # Move workspaces between monitors
  - commands: ["move-workspace --direction left"]
    bindings: ["lwin+shift+e"]

  - commands: ["move-workspace --direction right"]
    bindings: ["lwin+shift+w"]

window_rules:
  # Move to workspace 1
  - commands: ["move --workspace 1"]
    match:
      - window_process: { regex: "msedge" }

  # Move to workspace 2
  - commands: ["move --workspace 2"]
    match:
      - window_process: { regex: "WindowsTerminal" }

  # Move to workspace 5
  - commands: ["move --workspace 5"]
    match:
      - window_process: { regex: "ms-teams" }

  # Floating rules
  - commands: ["toggle-floating --centered"]
    match:
      - window_title: { regex: "Window Spy (.*)" }


  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore task manager
      - window_process: { equals: "Taskmgr" }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
